FloorMapFromSLAM:
  extract_contour_first: true        # bool
  epsilon: 0.001                     # float
  min_area: 100                      # int
  kernel_size: 3                     # int
  dilate_iteration: 2               # int

  Hough_thresh: 60                  # int
  Hough_minLength: 50              # int
  Hough_maxGap: 10                 # int

  refinement: true                  # bool

  output_vector_image: true       # bool
  room_num: "room1"                # str
  simple_output: false              # bool
  output_format: ".png"              # string

remove_redundant_lines:
  angle_thresh: 5.0               # float (degrees)
  distance_thresh: 10.0             # float (pixels)
  length_thresh: 15.0              # float (pixels)

contour_completion:
  horizon: 8                       # int
  sort: "yc"                       # str
  ascending: false                 # bool

  thresh_parallel: 5.0            # float (degrees)
  thresh_perp: 5.0                 # float (degrees)
  thresh_collinear: 10.0           # float (pixels)
  thresh_dist: 15.0                # float (pixels)

  min_seg_length: 30                  # int
  max_closepoint_dist: 200            # int
